### ISSUE TITLE
Git client

### ISSUE THREAD

**Issue by pydefre** [halcyon-tech/code-for-ibmi#127]
Hi,
How to setup my home directory to works with code for ibmi.
I'm new to git :)

Thanks for your help

**Comment by worksofliam** [comment]
I don't really understand the question. 

What are you trying to achieve with the extension?

**Comment by pydefre** [comment]
Sorry,
I would like to use the git client ibm i extension with code for ibmi.
You say "It will assume that your home directory, set in Code for IBM i is also a git repository" so in my home directory /home/MyUser, I have created the ibmi_src.git directory and processed to a git init --bare --shared 
after change my setting   "homeDirectory": "/home/MYUSER/ibmi_src.git/",
my source control view
<img width="381" alt="image" src="https://user-images.githubusercontent.com/746599/114278621-f84f8200-9a30-11eb-8dac-ee763d90f0d1.png">

... I'm starting with git and I don't understand what are the steps to use source control with code for ibm I extension

thanks for your help.

**Comment by SJLennon** [comment]
Note that I am not a Git expert and I have not used it for source control on the IBM i.  I know enough to have a Git repository on my PC and use GitHub Desktop (https://desktop.github.com/) to push code to Github.com.  Presently I manually move my IBM i source to my PC. 

I have not seriously looked at the git-client-ibmi extension (https://github.com/halcyon-tech/git-client-ibmi) until now.  **It is not clear to me if you need to install Git on the IBM i.**

I read this book to get an overview of Git:  https://git-scm.com/book/en/v2.  It's is free.  Costs nothing.
@pydefre

**Comment by SJLennon** [comment]
I played around with Git and got some results that may help move your forward.
1) I installed Git on the IBM i
2) I created a directory `/home/lennons/gittest`
3) Using PuTTY I connected to the IBM i 
4) Did `cd gittest`
5) Then `git init my-repo` which gives `Initialized empty Git repository in /home/LENNONS/gittest/my-repo/.git/`
6) Went back to the green screen and copied a file called `States.sql` to the ifs directory `my-repo`
6) Back in code-for-ibm I changed my IFS  browser to `/home/lennons/gittest/my-repo`

Now is source control I see this:
![image](https://user-images.githubusercontent.com/67484051/114603865-3da8c500-9c66-11eb-81b8-aefc216ab81c.png)
I can open the States.sql in the IFS browser:
![image](https://user-images.githubusercontent.com/67484051/114604874-739a7900-9c67-11eb-845f-b0197693877c.png)

I expect you could use QP2TERM on the green screen instead of using PuTTY.
@pydefre

**Comment by pydefre** [comment]
Thanks to you @SJLennon. This is exactly what I do
<img width="483" alt="image" src="https://user-images.githubusercontent.com/746599/114660789-36c99300-9cf6-11eb-9159-76426338415e.png">

perhaps something is wrong in my ibmi conf or access rights, i will check this

**Comment by SJLennon** [comment]
@pydefre In  your IFS browser, are you seeing the `.GIT` directory and all it's contents?  That would have been created when you did `GIT INIT` on the IBM i.
![image](https://user-images.githubusercontent.com/67484051/114723862-00e1da00-9d09-11eb-8a39-ca1a9d01e93b.png)

**Comment by SJLennon** [comment]
@pydefre Another thought:  You said you did `git init --bare --shared` and the `bare` might be the issue.  I simply did `git init`.
On this [page](https://www.saintsjd.com/2011/01/what-is-a-bare-git-repository/) it says that bare repos have a different directory structure.  Possibly the extension is looking for a "non bare" directory structure.  

Quoting from bottom of that same page:

> To summarize
> 
> I use a working directory created with git init or git clone when I want to add, edit and delete files in myproject locally on my dev machine.
> 
> When I am ready, I share my local changes with a git push to a bare repository myproject.git (usually on a remote server like github.com) so other developers can access my local changes.

But like I said, I'm not a Git expert.

**Comment by pydefre** [comment]
@SJLennon yes I see .git directory 
<img width="301" alt="image" src="https://user-images.githubusercontent.com/746599/114744653-365ce680-9d4e-11eb-9983-db990796b301.png">
with your comment, I have used git init my-repo.

My new test with QP2TERM
<img width="847" alt="image" src="https://user-images.githubusercontent.com/746599/114745867-65278c80-9d4f-11eb-9960-5e3e51683388.png">
in my green screen CPYTOSTMF a member in my /home/fvenditti/git_repo/ibmi_testing/test.txt
in vscode, i change my ifs folder 
<img width="847" alt="image" src="https://user-images.githubusercontent.com/746599/114748537-51c9f080-9d52-11eb-9cb3-f0be87112ea4.png">
<img width="419" alt="image" src="https://user-images.githubusercontent.com/746599/114748595-5ee6df80-9d52-11eb-9544-0d735daaf2f5.png">

in source control view
<img width="419" alt="image" src="https://user-images.githubusercontent.com/746599/114748739-7d4cdb00-9d52-11eb-87a3-650d83868098.png">

perhaps this git repo is accessible with sourcetree :(
<img width="538" alt="image" src="https://user-images.githubusercontent.com/746599/114749076-d61c7380-9d52-11eb-94f8-639d631bc724.png">

**Comment by SJLennon** [comment]
Sorry, doesn't look like I can contribute further, but you have helped me learn more about Git.  
Seems like it is something in the extension and I don't know enough about extension coding to check the code or try debugging it.  
Could it be something to do with the CCSID on the repo?  Mine is 1208. Which is interesting, since my interactive 5250 session is 37 (USA), /home is 37, and I'm running on PUB400.COM in Germany which defaults to 273.
From WRKLNK:
Object . . . . . . :   /home/LENNONS/gittest/my-repo  
                                                      
Type . . . . . . . . . . . . . . . . . :   DIR        
                                                      
Owner  . . . . . . . . . . . . . . . . :   LENNONS    
System object is on  . . . . . . . . . :   Local      
Auxiliary storage pool . . . . . . . . :   1          
  Object overflowed  . . . . . . . . . :   No         
                                                      
Coded character set ID . . . . . . . . :   1208       
@pydefre @worksofliam

**Comment by pydefre** [comment]
hi @SJLennon 

My Streamfile CCSID is 819, 5250 session CCSID is 1147. I don't check PUB400.COM but I suppose your are on V7R4 and I believe pase is now in UTF8. 
We are on V7R3.

<img width="857" alt="image" src="https://user-images.githubusercontent.com/746599/114815580-c33b8a80-9db6-11eb-9be9-52ebf1b49a41.png">

When I change my attribute directory and all branches to CCSID 1208, the problem is the same..

i will check with a friend on an other systemi :)

thanks a lot for your contributions
