### ISSUE TITLE
Improved implementation of the library list

### ISSUE THREAD

**Issue by szsascha** [halcyon-tech/code-for-ibmi#146]
Today I've tried code for ibmi the first time. Thank you for creating this great project!

At the beginning I was a bit confused by the implementation of the library list. I think with a few improvements the implementation of the libraries can be made a bit more intuitive and easier.

- Loading of the entire library list after login

Currently only the user part of the library list is loaded after login. In my opinion it would be better if the curlib and maybe the system part are also loaded at the beginning. In my current case (PUB400 default setup) all objects and sources are in my curlib.

- Use the curlib as the default build library

- Consolidate member browser and object browser to a library browser (libraries from library list should be added by default)

- Initialize files of member browser automatically by library

**Comment by worksofliam** [comment]
@szsascha 

These are some awesome suggestions. I am working on the search functionality today, but I will look into some of this for you.

> Loading of the entire library list after login

> Consolidate member browser and object browser to a library browser (libraries from library list should be added by default)

We actually had this way back when we started to develop this extension. The issue here is when there are thousands of objects and also thousands of source members. It wasn't pretty, hard to navigate, and even had some performance issues at times. It will have to stay like it is for now. You are able to right-click on source files from the object browser and add them to the member browser, though.

> Use the curlib as the default build library

This one is easy to do! Not sure why we didn't do this before.

**Comment by szsascha** [comment]
@worksofliam 

Thanks for your quick reply!

> We actually had this way back when we started to develop this extension. The issue here is when there are thousands of objects and also thousands of source members. It wasn't pretty, hard to navigate, and even had some performance issues at times. It will have to stay like it is for now. You are able to right-click on source files from the object browser and add them to the member browser, though.

Are there any other possibilities? Maybe you could install some kind of agent on the IBM i. I don't know if that solves this problem, but it might open up new possibilities elsewhere. Just an idea that came to me randomly.

> Are you suggesting we search through all objects your library list and add all source files to the member browser?

Yes. exactly. But I guess this will also lead to performance issues?
