### ISSUE TITLE
Source member list refresh at top refreshes all current source files. Could be slow.

### ISSUE THREAD

**Issue by richardschoen** [halcyon-tech/code-for-ibmi#31]
Is there a way to only refresh the selected source file in case a developer has several source files in their list ?

Ex: Click on source file and then click the refresh icon at the top. 

If this change is made title it: "Refresh Selected Source File" instead of "Refresh Member List"

Another option would be to just re-add the Right-Click option at the source file level to just refresh the selected source file.

**Either way the idea is to NOT have to refresh all members across all my source files in the list all the time.**

**Comment by worksofliam** [comment]
As far as I could tell there isn't a particularly easy way or obvious way to do it. I will leave it open.

**Comment by richardschoen** [comment]
You had a right-click before at the source file level.   Was that just triggering a refresh of entire list for all source files ?  I'm guessing  you are calling the refresh code for each source file., but I didn't dig in and look.

**Comment by worksofliam** [comment]
@richardschoen Even the right-click option that was there before was refreshing the entire menu.

**Comment by barrettotte** [comment]
@worksofliam @richardschoen I have a little attempt to add this functionality. It involves a bit of in-memory caching so it might not be very performant. But, I think I was able to get it working with [this commit](https://github.com/barrettotte/code-for-ibmi/commit/c418ca91855c497b521b15e6db23d934ac536041). 

Summary:
- when building tree view of members, check cache for key 'LIB/SPF'
  - If exists, pull from cache
  - else, query IBM i for member list
- refresh at top of member browser works as before
- right click context menu "Refresh Source File" added
  - performs targeted refresh on 'LIB/SPF', while reading other member lists from cache
- changed refresh logic in individual member commands if autorefresh enabled
  - create, delete, rename, updateText performs targeted refresh on LIB/SPF
  - copy does targeted refresh on source and destination

I still want to test it out more because my knowledge of the vscode extension API and JavaScript as a whole is lacking.
So, I'm afraid it may have side effects I'm not aware of yet.

**Comment by worksofliam** [comment]
@barrettotte That change makes a lot of sense, actually. I like it.

Whenever you feel ready, make a PR and I'd love to take it for a whirl. Thanks a lot.

**Comment by worksofliam** [comment]
Thanks @barrettotte for getting this one!
