### ISSUE TITLE
No obvious way to close a connection

### ISSUE THREAD

**Issue by JonFP** [halcyon-tech/code-for-ibmi#37]
I have two systems that I connect to regularly.  If I try to open a second connection while one is active, I get an error telling me there is already an active connection.  But I can find no obvious way to disconnect from one and connect to the other.

I'm probably just missing something but ...

**Comment by worksofliam** [comment]
Nope, you aren't missing anything. Right now, there isn't a way to disconnect from the existing system. Let me work on that for 0.0.14

**Comment by worksofliam** [comment]
Available in 0.0.14.. coming out very soon

**Comment by SJLennon** [comment]
@worksofliam @JonFP 
This is good and answered a question I was about to ask.  Kudos for quick fixes!

However, I see a problem if there are unsaved changes in an editor. 

I was connected. Made a changed to a file, but did not save.  Then I did F1, then "Connect to previous" and immediately it closed my first connection.  Now I have that editor still open with an unsaved change and no connection. 

I abandoned the connect dialog. By messing around and exploring save options to a closed connection I managed to get to the point where I had an open editor that I couldn't close, and reconnecting also seemed to be fouled up.  I has to restart VSCODE.  I could probably recreate my steps if necessary, but ...

I think there may need to be a warning if there are unsaved changed.  Easiest way would probably just give a warning and ignore the disconnect/reconnect request.

Or you could go further and give and option to abandon the changes and go ahead with the disconnect,  but then I think you would have to programmatically close the open editors.  Don't know if this is easy, but the EXPLORER has a "Close all Editors" button.

**Comment by worksofliam** [comment]
That's a great point! I think for now the best option is to close the saved files, but then switch to a file that isn't saved. I've pushed this up and will be available in 0.1.1

**Comment by SJLennon** [comment]
@worksofliam  @JonFP
I tested the change....
Minor typo I suspect:
    Cannot disconnect while files have **_no_** saved.
Probably should be:
    Cannot disconnect while files have not been saved.
Or perhaps
    Cannot disconnect:  File(s) changed but not saved.

Also, minor.  I have three files open.  The middle one has been changed.
![image](https://user-images.githubusercontent.com/67484051/109350914-58ee7b00-7846-11eb-8eb1-0d48ecdb88e4.png)
I do F1 and Connect to previous.  I get two messages.
![image](https://user-images.githubusercontent.com/67484051/109349233-9f8ea600-7843-11eb-83f3-2857e6b506f1.png)
I don't think the bottom one should be there.  I wait and it goes away after a short delay, maybe 15 seconds.  Good.  Then a second or so later the second goes away.  
The left file closes, focus goes to the open file, but the third file is still there:
![image](https://user-images.githubusercontent.com/67484051/109351177-d1553c00-7846-11eb-89dc-303fd9c0d649.png)

From experimenting a bit, it seems like files to the right of the changed file that gets the focus are not closed.

You have closed the original issue--should I be opening a new issue instead of adding to this one?

**Comment by worksofliam** [comment]
Thanks for your feedback!

1. Yes, looks like I need to update that text.
2. You can close the messages. They are just information and don't do anything whether they're open or not. E.g. you don't have to wait for them to close.
3. It looks like the connect should not happen unless the disconnect from the previous connection is successful. I can do that.
4. It's closing files left to right (it's an array of open editors) and stops when it finds the first one that is dirty (not saved). Maybe this logic should change to close all saved files before, but this isn't a major issue.

**Comment by worksofliam** [comment]
@SJLennon I have change the disconnect process in that:

* it will now close all saved files
* it will not let you connect to another system while you have unsaved files

This might solve the little things here and will be available in 0.1.2 later today.

**Comment by worksofliam** [comment]
I am gonna close this for now, but please open again if you have any more issues @SJLennon
