### ISSUE TITLE
Make database results pretty

### ISSUE THREAD

**Issue by worksofliam** [halcyon-tech/code-for-ibmi#61]
We're using a webview with a very simple HTML table to render SQL resultsets.

![image](https://user-images.githubusercontent.com/3708366/109563021-3316df80-7aad-11eb-99da-43c5ce14ead1.png)

Wondering if anyone would be able to make the table prettier? I have no idea how we should do it, really!

**Comment by SGI495** [comment]
@worksofliam I started playing around with this a bit. Since it's just a web view it's possible to do pretty much anything supported by Chromium and CSS. 

To begin I added some zebra striping and fonts based on VSCode editor settings and prevented line breaks in the table cells. There's more nuance required in the color settings to make it good, but at least it's a start I think. 

<img width="417" alt="Screenshot 2021-03-02 at 20 07 07" src="https://user-images.githubusercontent.com/653292/109701542-6df34300-7b93-11eb-8424-622d40e7219f.png">

<img width="1051" alt="Screenshot 2021-03-02 at 20 07 25" src="https://user-images.githubusercontent.com/653292/109701578-764b7e00-7b93-11eb-9d07-6460265852b7.png">

<img width="734" alt="Screenshot 2021-03-02 at 20 10 58" src="https://user-images.githubusercontent.com/653292/109701589-79466e80-7b93-11eb-8f07-ddcac3945b2b.png">

**Comment by worksofliam** [comment]
This is awesome @SGI495! Great work. Can't wait this PR lol!

**Comment by worksofliam** [comment]
Hey @SGI495! Wondering what the status is with this new look!

**Comment by SGI495** [comment]
@worksofliam Hey, I'm aiming to have a PR ready tonight!

**Comment by SGI495** [comment]
@worksofliam There's the PR. I think it looks ok in most of the default themes, including the high contrast one. It's basically using VSCode theme variables where possible, so the view probably won't feel out of place at least. The selection color is a bit low contrast in two or three themes but I couldn't really find a better one. Although I'm sure a designer could do something much better with this 😄 

Adding more features other than color I think might require some more metadata about the table being presented. Things like left aligning character fields, but right aligning numeric fields, as well as presenting information about the column attributes for example.
